name: CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run production
    - name: Commit built assets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -B test
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin test
    - name: Deploy to development
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SERVER_HOST }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
        cd ${{ secrets.PROJECT_PATH }}
        (php artisan down --message 'The app is being (quickly!) updated. Please try again in a minute.') || true
        git fetch origin test
        git reset --hard origin/test
        composer install --no-interaction --prefer-dist --optimize-autoloader
        php artisan migrate --force
        php artisan queue:restart
        php artisan optimize
        php artisan up
        echo "Application deployed!"


